# Generated by Django 3.2.6 on 2021-09-07 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('about_product', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='img')),
                ('price', models.CharField(max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategorymodel')),
            ],
        ),
    ]
